image: clarisys/gitlabci:trusty
stages: [build, deploy]
.build:
  stage: build
  variables:
    PGO_ENABLED: 1
  before_script:
    - >
      [ ! -z "$SSH_PRIVATE_KEY" ] && eval $(ssh-agent -s) && ssh-add <(echo "$SSH_PRIVATE_KEY") && SSH_PRIVATE_KEY=""
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 40
    - update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 40
    - update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-9 40
    - update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-9 40
  script:
    - VERSION=$(bin/checkupdate.sh -owner python -repository cpython -match "${MATCH}" -quiet)
    - bin/openssl.sh
    - bin/build.sh "${VERSION}"
    - test ! -z "$UPLOAD_URL" && scp python-*.tar.xz "${UPLOAD_URL}"
  artifacts:
    paths:
      - python-*.tar.xz

build:37:
  extends: .build
  variables:
    MATCH: ">=3.7.0,<3.8"
build:38b:
  extends: .build
  variables:
    MATCH: ">=3.8.0b"
build:38b_withoutpgo:
  extends: .build
  variables:
    MATCH: ">=3.8.0b"
    PGO_ENABLE: 0

