language: c
dist: trusty
sudo: required

before_install:
  - export CC=gcc-7

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - libncurses5-dev
      - zlib1g-dev
      - libssl-dev
      - libbz2-dev
      - libgdbm-dev
      - libsqlite3-dev
      - liblzma-dev
      - libreadline-dev
      - autoconf
      - automake
      - git-core

script:
  - bash bin/build.sh

