name: build
on: workflow_dispatch
jobs:
  main:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        PYTHON_MATCH: [">=3.9,<3.10"]
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - run: docker pull ghcr.io/zehome/python-portable-build:latest
      - uses: actions/checkout@v2
      - run: echo PYTHON_VERSION=$(bin/checkupdate.sh -owner python -repository cpython -match "${PYTHON_MATCH}" -quiet) >> $GITHUB_ENV
        env:
          PYTHON_MATCH: ${{ matrix.PYTHON_MATCH }}
      - run: docker run --ulimit nofile=1024:2048 --rm -v "$(realpath .):/ci" -w /ci -e "MATCH=${PYTHON_MATCH}" ghcr.io/zehome/python-portable-build make build
        env:
          PYTHON_MATCH: ${{ matrix.PYTHON_MATCH }}
      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: python-portable-${PYTHON_VERSION}
          path: build/python-*.tar.xz
