name: build
on: workflow_dispatch
jobs:
  main:
    strategy:
      matrix:
        PYTHON_MATCH: [">=3.7,<3.8", "3.8,<3.9", ">=3.9,<3.10"]
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - docker pull ghcr.io/zehome/python-portable-build:latest
      - uses: actions/checkout@v2
      - docker run --rm -v "$(realpath .):/ci" -w /ci -e "MATCH=${PYTHON_MATCH}" ghcr.io/zehome/python-portable-build make build

      - uses: actions/upload-artifact@v2
        with:
          name: python-portable
          path: build/python-*.tar.xz
